### ISSUE TITLE
[Backoffice] Header

### ISSUE THREAD

**Issue by chrisdugne** [CoorpAcademy/components#5]
# Goal

Use only components to build the [BO](https://github.com/CoorpAcademy/coorpacademy-backoffice/) header
# Tasks

These tasks start #4 
## atom
- [ ] icon
- [ ] label
- [ ] header-left
- [ ] header-right
- [ ] logo  (https://github.com/CoorpAcademy/coorpacademy-backoffice/issues/114)
- [ ] brand
## molecule
- [ ] icon-text
## organism
- [ ] header
- [ ] header-link
- [ ] header-link-dropdown 
## templates
- [ ] prepare a grid system
#### controls
- [ ] clickable
#### alignments
- [ ] text-align-center
#### colors
- [ ] text-normal
